version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Containerfile
    container_name: logzord-backend
    ports:
      - "3001:3001"
    volumes:
      # Montagem do arquivo de targets e do diretório de logs para leitura (ro = read-only)
      - ./backend/targets.json:/app/targets.json:ro
      - ./wkr:/app/wkr:ro
      - /var/log:/var/log:ro
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./frontend
      dockerfile: Containerfile
    container_name: logzord-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    restart: unless-stopped